spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}/${POSTGRES_DB:text}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  jpa:
    generate-ddl: true

  zipkin:
    base-url: http://zipkin:9411/
    service:
      name: "text-analyzer"
  main:
    allow-bean-definition-overriding: true
feign:
  url:
    auth: ${AUTH_SERVICE:http://auth-service:9999/}


service:
  return_top: 100
  send_sentry_top: 20
  #path-to-stop-words: ./stop_words.txt


management:
  endpoints:
    web:
      exposure:
        include: auditevents, beans, caches, conditions, configprops, health, httptrace, info, loggers, metrics, mappings, shutdown

